import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-[650px] border border-white/20 p-5 mx-auto my-10 space-y-8">
        <h2 className="title_lg">Lorem ipsum dolor sit amet.</h2>
        <h2 className="title_md">Lorem ipsum dolor sit amet.</h2>
        <h2 className="title_sm">Lorem ipsum dolor sit amet.</h2>
        <p className="subtitle_md">Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat consectetur nobis doloremque vero fugiat inventore optio dignissimos iusto maiores officiis voluptates commodi error iure asperiores deserunt tenetur fuga cupiditate tempora delectus vel odio, eligendi quasi ex. Doloribus dignissimos architecto unde ullam perferendis earum qui aliquid ea minima debitis. Molestiae, quaerat.</p>
        <p className="subtitle_sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat consectetur nobis doloremque vero fugiat inventore optio dignissimos iusto maiores officiis voluptates commodi error iure asperiores deserunt tenetur fuga cupiditate tempora delectus vel odio, eligendi quasi ex. Doloribus dignissimos architecto unde ullam perferendis earum qui aliquid ea minima debitis. Molestiae, quaerat.</p>
        <button
          style={{
            background: "linear-gradient(#000,#000) padding-box,linear-gradient(270deg, #2E27FE 0%, #9A12FF 73.96%, #CD05FF 100%) border-box"
          }}
          className="font-inter font-bold text-sm text-white px-[45px] py-3 border-2 border-transparent rounded-full">Learn More</button>
      </div>
    </>
  )
}
